### ISSUE TITLE
Deployment descriptions don't preserve newline characters

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#6450]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Deployment descriptions don't respect newline characters from docstrings

### Reproduction

- [ ] Make a deployment with a docstring description with newlines
- [ ] Look at the description in the UI

### Error

<img width="1177" alt="Screen Shot 2022-08-17 at 2 23 48 PM" src="https://user-images.githubusercontent.com/2325367/185217558-ed12dd56-4d47-4c96-99ed-3ee6cabb5f37.png">
 
Should be: 
```
    Retrieves recently finalized/sent Stripe invoices. Uses the Opportunity ID
    in the Stripe invoice metadata to find the related opportunity in SFDC and
    check the 'Invoice Submitted' checkbox for that opportunity.

    Parameters
    ----------
    sfdc_credentials_block_name: str = "sfdc-credentials"
        The name of the block containing the SFDC credentials to be used in the
        flow.
    stripe_api_key_block_name: str = "mark-sfdc-invoice-submitted-as-complete-strip-api-key"
        The name of the block containing the Stripe api key to be used in the
        flow.
    tms_twentyfour_hours_ago: float = None
        The current Unix Timestamp - 86400, as 86400 seconds = 24 hours.
        This allows us to retrieve only invoices finalized in the last 24 hrs.
        Defaults to 24 hours prior to the flow run expected start time.

    Returns
    -------
    None
```

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```

# Copy output of `prefect version` here if hosting your own UI

```

**Comment by madkinsz** [comment]
Just to confirm, the newline characters are present in the raw data stored by the API right?

**Comment by dylanbhughes** [comment]
Newline characters are present in the database, I'm not sure about returned values from the API

**Comment by felix-ht** [comment]
Any update on this? This makes the description mostly useless for anything but one-liners.

![image](https://user-images.githubusercontent.com/24698503/193404554-1865b0fa-170c-4cb6-9392-004b7b0b72d1.png)

![image](https://user-images.githubusercontent.com/24698503/193404572-b2a737a9-b21c-41a1-b79a-f49bda682d0b.png)

**Comment by dylanbhughes** [comment]
Definitely resolved!
