### ISSUE TITLE
When setting up a schedule via CLI or Python deployment, rrule is not parsed correctly in the UI

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#6740]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

```
prefect deployment build -n prod -q prod -a flows/hello.py:hello --rrule 'RRULE:FREQ=DAILY;COUNT=7;BYDAY=MO,TU,WE,TH,FR;BYHOUR=9'
```

![image](https://user-images.githubusercontent.com/86264395/189133167-b524f06c-de77-4670-b8b7-17114114f666.png)

### Reproduction

![image](https://user-images.githubusercontent.com/86264395/189132828-02bae253-c323-4965-8e41-3e4f0dc863bc.png)

### Error

the `byhour` part is skipped/not rendered

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```
Version:             2.3.2
API version:         0.8.0
Python version:      3.9.12
Git commit:          6e931ee9
Built:               Tue, Sep 6, 2022 12:36 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         hosted
```
