### ISSUE TITLE
Cancel button appears in UI for flow runs that cannot be cancelled

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#7736]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Only flow runs submitted by agents can be cancelled by the mechanism in #7666. The UI implementation originally hide the Cancel button for adhoc and subflow runs. In the current implementation, the cancel button appears for adhoc flow runs.

This could be fixed directly, but #7150 would allow any flow run to be cancelled so if we accomplish that by 2.7.1 we can skip this change.

### Reproduction

Run a flow locally that sleeps for a while.
Open the flow run page in the UI.

### Error

—

### Browers

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
❯ prefect version    
Version:             2.7.0
API version:         0.8.3
Python version:      3.8.3
Git commit:          c2833339
Built:               Thu, Dec 1, 2022 4:03 PM
OS/Arch:             darwin/x86_64
Profile:             test
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```
