### ISSUE TITLE
Consolidate projects and deployments

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#9860]
The 'project' concept has become unnecessary as the new deployment UX has developed and can be removed to avoid conflation with the 'project' concept from Prefect 1.0. Remove mentions of 'projects' from Prefect 2. This will impact the following areas:

### Functionality

- [x]  Remove creation and use of the `.prefect` folder that is currently created by `prefect project init`

- [x]  Remove the ability to deploy a flow with a flow name and instead use entrypoint universally

### CLI

- [x]  `prefect project init` -> `prefect init`

- [x]  `prefect project recipe ls` -> `prefect init recipes ls`

- [x]  Remove `prefect project clone`

### Modules

- [ ]  `prefect.projects` -> `prefect.deployments`

    - Note that steps would now be referenced `prefect.deployment.steps.step_name`

- [ ]  `prefect_aws.projects` -> `prefect_aws.deployments`

- [ ]  `prefect_gcp.projects` -> `prefect_gcp.deployments`

- [ ]  `prefect_azure.projects` -> `prefect_azure.deployments`

- [ ]  `prefect_docker.projects` -> `prefect_docker.deployments`

### Step Names

- [x]  `prefect`

     `git_clone_project` -> `git_clone`

- [ ]  `prefect-aws`

    - `pull_project_from_s3` -> `pull_from_s3`
    - `push_project_to_s3` -> `push_to_s3`

- [ ]  'prefect-gcp`

    - `pull_project_from_gcs` -> `pull_from_gcs`
    - `push_project_to_gcs` -> `push_to_gcs`

- [ ]  `prefect-azure`

    - `pull_project_from_azure_blob_storage` -> `pull_from_azure_blob_storage`
    - `push_project_to_azure_blob_storage` -> `push_to_azure_blob_storage`
